# .github/workflows/release-please.yml

name: Release please with Bot

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Use release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: terraform-module # Multiple release types are supported
          default-branch: master
